### ISSUE TITLE
indicator says "busy"

### ISSUE THREAD

**Issue by JimKatsanoss** [MichalW/gnome-bluetooth-battery-indicator#27]
This might have been addressed before.... any fixes?

Debug stuff:

Usage of object.actor is deprecated for Indicator
get@resource:///org/gnome/shell/ui/environment.js:317:29
_refresh@/home/jimkatsanos/.local/share/gnome-shell/extensions/bluetooth-battery@michalw.github.com/extension.js:84:13
_runLoop@/home/jimkatsanos/.local/share/gnome-shell/extensions/bluetooth-battery@michalw.github.com/extension.js:47:14

Bluetooth battery indicator: xxx is offline [Errno 16] Device or resource busy
- - - -
but im currently listening to music

**Comment by Etaash-mathamsetty** [comment]
same error
from journalctl
`Bluetooth battery indicator: Couldn't find the RFCOMM port number
D0:BC:C1:3A:5B:7E is offline [Errno 16] Device or resource busy
`

**Comment by 3laws** [comment]
From the **Troubleshoot** guide in the ReadMe

journalctl
`Bluetooth battery indicator: Couldn't find the RFCOMM port number
00:00:00:00:00:00 is offline [Errno 111] Connection refused
`

py script
`py ~/Downloads/bluetooth_battery.py 00:00:00:00:00:00
Traceback (most recent call last):
  File "/home/user/Downloads/bluetooth_battery.py", line 166, in <module>
    main()
  File "/home/user/Downloads/bluetooth_battery.py", line 162, in main
    query = BatteryStateQuerier(*device.split("."))
  File "/home/3laws/Downloads/bluetooth_battery.py", line 81, in __init__
    self._bt_settings = bluetooth_mac, int(bluetooth_port or RFCOMMSocket.find_rfcomm_port(bluetooth_mac))
  File "/home/user/Downloads/bluetooth_battery.py", line 60, in find_rfcomm_port
    raise bluetooth.BluetoothError("Couldn't find the RFCOMM port number. Perhaps the device is offline?")
bluetooth.btcommon.BluetoothError: Couldn't find the RFCOMM port number. Perhaps the device is offline?
`

**Comment by stem-lg** [comment]
same
![image](https://user-images.githubusercontent.com/37732484/156913947-e5a7c724-bf91-4e88-9071-392e299bd5f7.png)

**Comment by matan129** [comment]
Getting this error too (with Airpods Pro). Any ideas? @MichalW

**Comment by Etaash-mathamsetty** [comment]
use a diferent extension, it's at https://extensions.gnome.org/extension/1401/bluetooth-quick-connect/ , it does a similar thing as this extension, along with making it easier to connect bluetooth devices.

**Comment by matan129** [comment]
I'm already using that extension, it's pretty nice indeed. But it also doesn't display the battery level (if even I tick that option on).

**Comment by Etaash-mathamsetty** [comment]
> I'm already using that extension, it's pretty nice indeed. But it also doesn't display the battery level (if even I tick that option on).

I am no longer using gnome, so I don't think I can help you there

**Comment by kred-jon** [comment]
try using Upower script.

https://github.com/MichalW/gnome-bluetooth-battery-indicator/issues/44#issuecomment-1233842251

**Comment by matan129** [comment]
Upower doesn't work with Airpods Pro (mine, at least, running latest Arch stuff).

I did [fork this repo](https://github.com/matan129/gnome-bluetooth-battery-indicator) and integrated it with [my own fork of AirStatus](https://github.com/matan129/AirStatus).

I consider its quality to be not that great, because of [this limitation](https://github.com/matan129/gnome-bluetooth-battery-indicator/blob/869750b6d4502674b7bd6292ec3348077d51b186/extension.js#L113-L115) - so for now I'm not sure if it's a good idea to try and merge it to this repo.

Having said that, my fork shows left and right batter levels:
![image](https://user-images.githubusercontent.com/1483099/188011529-88b33b00-8e1d-4909-a9f6-ab466f8cbd72.png)

With this new config option:
![image](https://user-images.githubusercontent.com/1483099/188011617-2119e8ee-f82b-46b0-90ec-81c59db3f4d8.png)


@MichalW - do you think it's good enough the merge? We can add a notice of that limitation in the readme.

**Comment by andirsun** [comment]
@matan129 you had to manually install AirStatus on the background because I install your extension fork and didnt work. I am using AIrpods pro
